package main

import "net/http"

// securityHeaders applies response-security policy consistently to every route,
// including responses generated by the router for unmatched paths.
func securityHeaders(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		headers := w.Header()
		headers.Set("Cache-Control", "no-store")
		headers.Set("Content-Security-Policy", "default-src 'none'")
		headers.Set(
			"Permissions-Policy",
			"camera=(), geolocation=(), microphone=()",
		)
		headers.Set("Referrer-Policy", "no-referrer")
		headers.Set("X-Content-Type-Options", "nosniff")
		headers.Set("X-Frame-Options", "DENY")

		next.ServeHTTP(w, r)
	})
}
